basePath: /api/v1
definitions:
  internal_app_api.CustomerItem:
    properties:
      address:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
    type: object
  internal_app_api.OrderListItem:
    properties:
      customer:
        $ref: '#/definitions/internal_app_api.CustomerItem'
      id:
        type: string
      status:
        type: string
    type: object
  internal_app_api.UserInfoItem:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact: {}
  title: jokerge
  version: "1.0"
paths:
  /api/auth:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app_api.UserInfoItem'
      summary: валидация пользовательских данных
      tags:
      - auth
  /api/v1/customer:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: создание нового клиента
      tags:
      - customers
  /api/v1/customer/{customer_id}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app_api.CustomerItem'
      summary: информация о клиенте
      tags:
      - customers
  /api/v1/customer/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_app_api.CustomerItem'
            type: array
      summary: список клиентов
      tags:
      - customers
  /api/v1/order:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: создаение заказа
      tags:
      - orders
  /api/v1/order/{order_id}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app_api.OrderListItem'
      summary: информация о заказе
      tags:
      - orders
  /api/v1/order/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_app_api.OrderListItem'
            type: array
      summary: список заказов
      tags:
      - orders
  /api/v1/order/update:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - orders
swagger: "2.0"
