basePath: /
definitions:
  github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  github_com_ak1m1tsu_jokerge_internal_pkg_types.CustomerInfoOrderResponse:
    properties:
      created_at:
        type: string
      id:
        type: integer
      price:
        type: integer
      status:
        type: string
    type: object
  github_com_ak1m1tsu_jokerge_internal_pkg_types.CustomerInfoResponse:
    properties:
      address:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      orders:
        items:
          $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.CustomerInfoOrderResponse'
        type: array
    type: object
  github_com_ak1m1tsu_jokerge_internal_pkg_types.OrderInfoCustomerResponse:
    properties:
      address:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
    type: object
  github_com_ak1m1tsu_jokerge_internal_pkg_types.OrderInfoProductResponse:
    properties:
      count:
        type: integer
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
  github_com_ak1m1tsu_jokerge_internal_pkg_types.OrderInfoResponse:
    properties:
      created_at:
        type: string
      customer:
        $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.OrderInfoCustomerResponse'
      id:
        type: integer
      price:
        type: integer
      products:
        items:
          $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.OrderInfoProductResponse'
        type: array
      status:
        type: string
    type: object
  github_com_ak1m1tsu_jokerge_internal_pkg_types.ProductInfoResponse:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
  github_com_ak1m1tsu_jokerge_internal_pkg_types.ValidateUserCredentialsResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
    type: object
  internal_app_api.ValidateUserReq:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact: {}
  title: jokerge
  version: "1.0"
paths:
  /api/auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: Тело запроса
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/internal_app_api.ValidateUserReq'
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.ValidateUserCredentialsResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
      summary: валидация пользовательских данных
      tags:
      - auth
  /api/v1/customer:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
      security:
      - BasicAuth: []
      summary: создание нового клиента
      tags:
      - customers
  /api/v1/customer/{customer_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID клиента
        in: path
        name: customer_id
        required: true
        type: string
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.CustomerInfoResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
      security:
      - BasicAuth: []
      summary: информация о клиенте
      tags:
      - customers
  /api/v1/customer/list:
    get:
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.CustomerInfoResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
      security:
      - BasicAuth: []
      summary: список клиентов
      tags:
      - customers
  /api/v1/order:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
      security:
      - BasicAuth: []
      summary: создаение заказа
      tags:
      - orders
  /api/v1/order/{order_id}:
    get:
      parameters:
      - description: ID заказа
        in: path
        name: order_id
        required: true
        type: integer
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.OrderInfoResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
      security:
      - BasicAuth: []
      summary: информация о заказе
      tags:
      - orders
  /api/v1/order/list:
    get:
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.OrderInfoResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
      security:
      - BasicAuth: []
      summary: список заказов
      tags:
      - orders
  /api/v1/order/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
      security:
      - BasicAuth: []
      summary: обновление информации о заказе
      tags:
      - orders
  /api/v1/product/{product_id}:
    get:
      parameters:
      - description: ID продукта
        in: path
        name: product_id
        required: true
        type: string
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.ProductInfoResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
      security:
      - BasicAuth: []
      summary: информация о продукте
      tags:
      - products
  /api/v1/produuct/list:
    get:
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.ProductInfoResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_ak1m1tsu_jokerge_internal_pkg_types.APIResponse'
      security:
      - BasicAuth: []
      summary: список продуктов
      tags:
      - products
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
