basePath: /
definitions:
  internal_app_api.CustomerItem:
    properties:
      address:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
    type: object
  internal_app_api.OrderListItem:
    properties:
      customer:
        $ref: '#/definitions/internal_app_api.CustomerItem'
      id:
        type: integer
      status:
        type: string
    type: object
  internal_app_api.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  internal_app_api.UserInfoItem:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
    type: object
  internal_app_api.ValidateUserReq:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact: {}
  title: jokerge
  version: "1.0"
paths:
  /api/auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: Тело запроса
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/internal_app_api.ValidateUserReq'
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app_api.UserInfoItem'
      summary: валидация пользовательских данных
      tags:
      - auth
  /api/v1/customer:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app_api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_app_api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_app_api.Response'
      summary: создание нового клиента
      tags:
      - customers
  /api/v1/customer/{customer_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID клиента
        in: path
        name: customer_id
        required: true
        type: string
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app_api.CustomerItem'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal_app_api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_app_api.Response'
      summary: информация о клиенте
      tags:
      - customers
  /api/v1/customer/list:
    get:
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_app_api.CustomerItem'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_app_api.Response'
      summary: список клиентов
      tags:
      - customers
  /api/v1/order:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app_api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_app_api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_app_api.Response'
      summary: создаение заказа
      tags:
      - orders
  /api/v1/order/{order_id}:
    get:
      parameters:
      - description: ID заказа
        in: path
        name: order_id
        required: true
        type: integer
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app_api.OrderListItem'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal_app_api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_app_api.Response'
      summary: информация о заказе
      tags:
      - orders
  /api/v1/order/list:
    get:
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_app_api.OrderListItem'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_app_api.Response'
      summary: список заказов
      tags:
      - orders
  /api/v1/order/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID запроса
        in: header
        name: X-Request-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app_api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_app_api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_app_api.Response'
      tags:
      - orders
swagger: "2.0"
